---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker.artifactory.platform.manulife.io/hk-java-cf-flyway
    tag: "latest"

inputs:
- name: concourse-pipeline-samples

outputs:
- name: current-app-info

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info
