groups:
- name: main
  jobs:
  - deploy-app

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/lxyoutlook/concourse-pipeline-samples.git
- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
  - task: prepare-app-manifest
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
  - put: PWS
    params:
      manifest: app-manifest-output/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
